-- Supabase schema reference for the eFootball Tournament app.
-- The connected project already contains the required RPCs.
create extension if not exists pgcrypto;
create schema if not exists private;
create table if not exists public.tournaments (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, description text not null default '', status text not null default 'draft' check(status in ('draft','group_stage','knockout_stage','completed')), champion_id uuid, created_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now());
create table if not exists public.participants (id uuid primary key default gen_random_uuid(), tournament_id uuid not null references public.tournaments(id) on delete cascade, name text not null, group_name text check(group_name in ('A','B')), player_token text not null, created_at timestamptz not null default now(), unique(tournament_id,name), unique(tournament_id,player_token));
create table if not exists public.matches (id uuid primary key default gen_random_uuid(), tournament_id uuid not null references public.tournaments(id) on delete cascade, stage text not null check(stage in ('group','knockout')), group_name text check(group_name in ('A','B')), matchday integer, round text check(round in ('semi','final','third')), slot integer, home_id uuid not null references public.participants(id) on delete cascade, away_id uuid not null references public.participants(id) on delete cascade, home_score integer check(home_score is null or home_score>=0), away_score integer check(away_score is null or away_score>=0), winner_id uuid references public.participants(id) on delete set null, penalties text, status text not null default 'scheduled' check(status in ('scheduled','completed','cancelled')), submitted_by text, submitted_at timestamptz, updated_at timestamptz not null default now(), check(home_id<>away_id), check(winner_id is null or winner_id=home_id or winner_id=away_id));
create table if not exists private.tournament_secrets (tournament_id uuid primary key references public.tournaments(id) on delete cascade, admin_token text not null);
alter table public.tournaments enable row level security;
alter table public.participants enable row level security;
alter table public.matches enable row level security;
